# Pull node image
FROM node:12.17.0-alpine3.11 as build
# set working directory
WORKDIR /app

# install plug-ins
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

#copy and build
COPY . ./
RUN npm run build


# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# Steps to run in local
# docker build -f Dockerfile.prod -t  samplereact
# docker run -it --rm -p 1337:80 samplereact